### ISSUE TITLE
Final Predictions in Script 05

### ISSUE THREAD

**Issue by Z-Richardson** [sfirke/predicting-march-madness#8]
I may be incorrect, but should the Pred = stage_1_preds part of this code be replaced with Pred = final_preds_1? 

_**Current:**_
final_preds_to_send <- final_blank %>%
  dplyr::select(id) %>%
  mutate(Pred = stage_1_preds)

**_Should Be:_**
final_preds_to_send <- final_blank %>%
  dplyr::select(id) %>%
  mutate(Pred = final_preds_1)

**Comment by sfirke** [comment]
Right you are!  I just fixed, see if that does it.  Thanks for flagging this.

**Comment by Z-Richardson** [comment]
Yup works perfect now, thank you.
